name: split_the_bill
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  rive: ^0.9.1
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  awesome_bottom_bar: ^1.2.1
  image_picker: ^0.8.6
  photo_view: ^0.14.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  flutter_downloader: ^1.10.1
  permission_handler: ^10.2.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.8
  modal_bottom_sheet: ^2.1.2
  flutter_chat_ui: ^1.6.6
  flutter_firebase_chat_core: ^1.6.4
  flutter_chat_types: ^3.6.0
  file_picker: ^5.2.5
  mime: ^1.0.4
  open_filex: ^4.3.2
  uuid: ^3.0.7
  connectivity_wrapper: ^1.1.1
  connection_notifier: ^1.0.1

  #firebase
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.1
  firebase_storage: ^11.0.8
  cloud_firestore: ^4.2.0
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-VariableFont_wght.ttf
        - asset: fonts/Raleway-Italic-VariableFont_wght.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-VariableFont_wght.ttf
        - asset: fonts/RobotoMono-Italic-VariableFont_wght.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
